kube-prometheus-stack:
  grafana:
    adminPassword: "admin"
    service:
      type: ClusterIP
    ingress:
      enabled: true
      ingressClassName: nginx
      hosts:
        - grafana.peter-ktb4.cloud
      paths: /

loki-stack:
  loki:
    enabled: true
  promtail:
    enabled: false
  file:
    datasource.yaml: |
      apiVersion: 1
      datasources:
        - name: Loki
          type: loki
          access: proxy
          url: "http://peter-monitoring-loki:3100"
          version: 1
          isDefault: false
