apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: peter-community-servicemonitor
  namespace: {{ .Release.Namespace }}
  labels:
    release: peter-monitoring
spec:
  selector:
    matchLabels:
      app: {{ .Values.appName }}
  endpoints:
    - port: http
      path: /actuator/prometheus
      interval: 10s
