appName: community-frontend

image:
  repository: peterj0117/community-frontend
  tag: "v1.0.6"
  pullPolicy: Always

service:
  name: peter-community-frontend-service # Ingress 연동용 고정명
  port: 80
  targetPort: 3000
